name: blochub
description: A real estate listing app.

version: 1.0.0+1

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #dependency injection
  get_it: ^4.0.2
  injectable: ^0.4.0

  #UI enhancement libs
  font_awesome_flutter: ^8.8.1

  #firebase related libs
  firebase_core: 0.4.5
  cloud_firestore: ^0.13.6
  firebase_analytics: ^5.0.14

  #auth related libs
  google_sign_in: ^4.4.4
  flutter_facebook_login: ^3.0.0

  #utilities related libsc
  shared_preferences: ^0.5.7+1
  http: ^0.12.1

  #code generator related libs
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  freezed_annotation:

  #linting related lib
  pedantic: ^1.9.0

  # flavor
  flutter_flavorizr: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  #font libs
  google_fonts: ^1.1.0

  #generate random uuid
  uuid: ^2.0.4

  #code generator related libs
  build_runner: ^1.9.0
  freezed: ^0.10.8
  injectable_generator: ^0.4.0

  #generate app icons for both ios and android
  flutter_launcher_icons: "^0.7.5"

  #testing related libs
  mockito: ^4.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_blochub.png"

flutter:
  uses-material-design: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "BlocHub Dev"

      android:
        applicationId: "com.madz.blochub.dev"

      ios:
        bundleId: "com.madz.blochub.dev"

    qa:
      app:
        name: "BlocHub QA"

      android:
        applicationId: "com.madz.blochub.qa"

      ios:
        bundleId: "com.madz.blochub.qa"

    prod:
      app:
        name: "BlocHub"

      android:
        applicationId: "com.madz.blochub.prod"

      ios:
        bundleId: "com.madz.blochub.prod"
