name: blochub
description: A real estate listing app.

version: 1.0.0+1

environment:
  sdk: ">=2.8.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #font libs
  google_fonts: ^1.1.0

  #dependency injection
  get_it: ^4.0.2
  injectable: ^0.4.0

  #UI libs
  font_awesome_flutter: ^8.8.1

  #bloc related libs
  flutter_bloc: ^4.0.0
  rxdart: ^0.24.0
  #equatable: ^1.2.0

  #firebase related libs
  firebase_core: 0.4.5
  cloud_firestore: ^0.13.6
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  firebase_analytics: ^5.0.14
  firebase_crashlytics: ^0.1.3+3

  #auth related libs
  google_sign_in: ^4.5.1
  flutter_facebook_login: ^3.0.0

  #utilities related libs
  image_picker: ^0.6.7
  shared_preferences: ^0.5.7+1
  http: ^0.12.1

  #google maps related libs
  google_maps_flutter: ^0.5.27+1
  geolocator: ^5.3.1
  location_permissions: ^2.0.5

  #code generator related libs
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  freezed_annotation:

  #linting related lib
  pedantic: ^1.9.0

  # flavor
  flutter_flavorizr: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  #generate random uuid
  uuid: ^2.0.4

  #code generator related libs
  injectable_generator: ^0.4.0
  freezed: ^0.10.8
  build_runner: ^1.9.0

  #generate app icons for both ios and android
  flutter_launcher_icons: "^0.7.5"

  #testing related libs
  mockito: ^4.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_blochub.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "BlocHub Dev"

      android:
        applicationId: "com.madz.blochub.dev"

      ios:
        bundleId: "com.madz.blochub.dev"

    qa:
      app:
        name: "BlocHub QA"

      android:
        applicationId: "com.madz.blochub.qa"

      ios:
        bundleId: "com.madz.blochub.qa"

    prod:
      app:
        name: "BlocHub"

      android:
        applicationId: "com.madz.blochub.prod"

      ios:
        bundleId: "com.madz.blochub.prod"
